import pyautogui as p
import time

def f():
    time.sleep(1)
    p.click(800, 870)
    time.sleep(0.5)
    p.click(756, 343)
    time.sleep(0.5)
    p.click(990, 805)
    time.sleep(8)
    p.press('d')
    p.keyDown('d')
    time.sleep(2)
    p.keyUp('d')
    p.press('o')
    time.sleep(1.5)
    p.press('l')
    p.press('a')
    p.keyDown('a')
    time.sleep(0.9)
    p.keyUp('a');
    time.sleep(0.7)
    p.press('l')
    p.press('d')
    p.keyDown('d')
    time.sleep(1.2)
    p.keyUp('d')
    p.press('l')
    time.sleep(2.6)
    p.press('l')
    time.sleep(2.1)
    p.press('l')
    # time.sleep(0.6)
    # p.press('i')
    time.sleep(2.6)
    p.press('space')
    p.press('l')
    time.sleep(2.1)
    p.press('l')
    time.sleep(2.6)
    p.press('l')
    p.press('a')
    p.keyDown('a')
    time.sleep(0.5)
    p.press('h')
    p.press('l',3,1.5)
    time.sleep(1.5)
    p.keyUp('a')
    p.click(1099,883)
    time.sleep(2.3)
    p.click(971,485)
    time.sleep(1)

for i in range(0, 200):
    f()
# print(p.position())

